import { randomUUID } from 'node:crypto';
import {
  accessSync,
  constants,
  lstatSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync
} from 'node:fs';
import { basename, join, resolve } from 'node:path';

const quoteZsh = (value: string): string => `'${value.replaceAll("'", "'\\''")}'`;

const restoreDirectory = `if [[ "\${_bitterless_zsh_zdotdir_type-}" == *export* ]]; then
  builtin export ZDOTDIR="\${_bitterless_zsh_zdotdir-}"
elif [[ -n "\${_bitterless_zsh_zdotdir_type-}" ]]; then
  builtin typeset +x ZDOTDIR
  ZDOTDIR="\${_bitterless_zsh_zdotdir-}"
else
  builtin unset ZDOTDIR
fi
builtin unset _bitterless_zsh_zdotdir_type _bitterless_zsh_zdotdir
`;

const forwardStartup = (
  file: string
): string => `if [[ -r "\${ZDOTDIR-$HOME}/${file}" || -r "\${ZDOTDIR-$HOME}/${file}.zwc" ]]; then
  builtin source "\${ZDOTDIR-$HOME}/${file}"
fi
`;

const routeNextStartup = (
  directory: string
): string => `if [[ -o interactive && -o rcs && "\${(t)ZDOTDIR-}" != *readonly* ]]; then
  _bitterless_zsh_zdotdir_type="\${(t)ZDOTDIR-}"
  _bitterless_zsh_zdotdir="\${ZDOTDIR-}"
  builtin typeset +x _bitterless_zsh_zdotdir_type _bitterless_zsh_zdotdir
  builtin export ZDOTDIR=${quoteZsh(directory)}
fi
`;

const loadHighlighter = (
  plugin: string
): string => `# User startup files and widgets have finished; preserve an existing highlighter or color opt-out.
if [[ -o interactive && -o rcs && -z "\${NO_COLOR-}" && -z "\${NODE_DISABLE_COLORS-}" ]] &&
   (( ! \${+functions[_zsh_highlight]} )) &&
   [[ -z "\${ZSH_HIGHLIGHT_VERSION-}" && -z "\${FAST_HIGHLIGHT_VERSION-}" ]]; then
  builtin source ${quoteZsh(plugin)}
fi
`;

const writeIfChanged = (file: string, source: string): void => {
  try {
    if (readFileSync(file, 'utf8') === source) return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  const temporary = `${file}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temporary, source, { flag: 'wx', mode: 0o600 });
    renameSync(temporary, file);
  } finally {
    rmSync(temporary, { force: true });
  }
};

/** Only the child receives these shims. User startup files retain their own ZDOTDIR and options. */
export const ensureZellijShellIntegration = (options: {
  profileDirectory: string;
  assetDirectory: string;
  selectedShell: string;
  explicitDefaultShell?: string | boolean | null;
  env: NodeJS.ProcessEnv;
}): NodeJS.ProcessEnv => {
  if (basename(options.selectedShell) !== 'zsh' || options.explicitDefaultShell) return options.env;

  const plugin = resolve(
    options.assetDirectory,
    'zsh-syntax-highlighting',
    'zsh-syntax-highlighting.zsh'
  );
  accessSync(plugin, constants.R_OK);
  const directory = resolve(options.profileDirectory, 'shell', 'zsh');
  mkdirSync(directory, { recursive: true, mode: 0o700 });
  const status = lstatSync(directory);
  if (
    !status.isDirectory() ||
    status.isSymbolicLink() ||
    (process.getuid && status.uid !== process.getuid()) ||
    status.mode & 0o077
  ) {
    throw new Error('operation-failed');
  }

  const header = '# Generated by Bitterless. User startup files are sourced, never edited.\n';
  const sources = {
    '.zshenv': `if [[ "\${BITTERLESS_ZSH_ORIGINAL_ZDOTDIR_SET-}" == 1 ]]; then
  builtin export ZDOTDIR="\${BITTERLESS_ZSH_ORIGINAL_ZDOTDIR-}"
else
  builtin unset ZDOTDIR
fi
builtin unset BITTERLESS_ZSH_ORIGINAL_ZDOTDIR_SET BITTERLESS_ZSH_ORIGINAL_ZDOTDIR
# Zellij omits -l; use native login startup so GUI launches inherit the user's command PATH.
# Apply before user .zshenv so an explicit unsetopt login still wins.
if [[ -o interactive && -o rcs ]]; then
  builtin setopt login
fi
${forwardStartup('.zshenv')}${routeNextStartup(directory)}`,
    '.zprofile': restoreDirectory + forwardStartup('.zprofile') + routeNextStartup(directory),
    '.zshrc': `${restoreDirectory}${forwardStartup('.zshrc')}if [[ -o login ]]; then
${routeNextStartup(directory)}else
${loadHighlighter(plugin)}fi
`,
    '.zlogin': restoreDirectory + forwardStartup('.zlogin') + loadHighlighter(plugin)
  };
  for (const [file, source] of Object.entries(sources))
    writeIfChanged(join(directory, file), header + source);

  return {
    ...options.env,
    BITTERLESS_ZSH_ORIGINAL_ZDOTDIR_SET: options.env.ZDOTDIR === undefined ? '0' : '1',
    BITTERLESS_ZSH_ORIGINAL_ZDOTDIR: options.env.ZDOTDIR ?? '',
    ZDOTDIR: directory
  };
};
