// The package a fresh install finds in its workflows folder. Kept inline so the seed does not depend
// on a file surviving packaging — the app has to be able to write it on a machine that never saw the
// repository. Generated from examples/institution-workflow/; edit there and re-copy, not here.
//
// Dynamic workflow (`workflow.mjs` + its own `export const meta`). There is no `workflow.json`:
// the retired packaging kept a manifest beside the entry and the two drifted, and a seeded package
// in the old shape now lands in the library as a red row saying it cannot be read.
export const sharedWorkflowDemoFiles: Record<string, string> = {
  "workflow.mjs": "export const meta = {\n  name: 'workflow-demo',\n  description: 'Proves the local workflows folder end to end: this package is listed, its script is readable, and it runs without a model, a network or an account. It reads nothing and writes nothing — the only output is a short report about the text you give it.',\n  whenToUse: 'Use when the owner wants to confirm the local workflows folder works end to end — that a package sitting in the workflows directory is listed, readable and actually runnable — or wants a plain word / line / character count of a short piece of text. The input is the text itself. Do NOT use it to read files, run commands, search, or answer questions about content: it reads nothing and only measures what it is handed.',\n  phases: [{ title: 'Measure' }, { title: 'Report' }]\n}\n\n/**\n * The offline demo package.\n *\n * **It calls no agent on purpose.** Its job is to answer one question — \"is the workflows folder\n * wired up?\" — and it has to be able to answer it while signed out, offline, and with no model\n * configured. Adding an agent would make the smoke test depend on the very things it exists to rule\n * out. That makes it the exception, not the pattern: a real workflow orchestrates agents.\n *\n * Everything it varies on arrives in `args`. Edit this file directly to change it; the host re-reads\n * the folder on every save.\n */\n\nconst text = typeof args === 'string' ? args : (args && (args.text ?? args.input)) || ''\nconst trimmed = String(text).trim()\n\nphase('Measure')\nconst words = trimmed ? trimmed.split(/\\s+/u).length : 0\nconst lines = trimmed ? trimmed.split(/\\r?\\n/u).length : 0\nlog('measured ' + words + ' word(s) in ' + trimmed.length + ' character(s)')\n\nphase('Report')\n// Deterministic by construction: the same input gives the same report on every machine and every\n// replay, which is what makes this usable as a smoke test rather than an illustration.\nconst message = 'Processed ' + words + ' words: ' + trimmed\n\nreturn { words, lines, characters: trimmed.length, message }\n",
  "README.md": "# workflow-demo\n\nThe package a fresh install finds in its workflows folder, so the first look at the Workflows view\nis a working example rather than an empty pane next to a directory nobody has heard of.\n\nIt exists to answer one question — **is the workflows folder wired up?** — and it has to be able to\nanswer it while signed out, offline, and with no model configured. So it calls no agent: adding one\nwould make the smoke test depend on the very things it is there to rule out. That makes it the\nexception. A real workflow orchestrates agents; this one measures a string.\n\n## Files\n\n- `workflow.mjs` — the entry. Its `export const meta` is the **only** source of what the library\n  shows: name, description, `whenToUse`, phases. There is no manifest beside it to drift from it.\n- `README.md` — this file.\n\n## Running it\n\nPass the text as the input:\n\n```text\nworkflow workflow-demo   Shared institution workflows work.\n```\n\n```json\n{ \"words\": 4, \"lines\": 1, \"characters\": 33, \"message\": \"Processed 4 words: Shared institution workflows work.\" }\n```\n\nWhitespace-only input is valid and returns `{\"words\":0,…,\"message\":\"Processed 0 words: \"}`.\n\nThe same input gives the same result on every machine and every replay — which is what makes it\nusable as a smoke test rather than an illustration.\n\n## Editing it\n\nOpen `workflow.mjs` and change it. The host re-reads the folder on every save: no rebuild, no\nre-import, no generator to run again. Deleting the package is a decision the app respects — it is\nseeded once, and a marker keeps the next launch from putting it back.\n\nIt reads no files, spawns no processes, makes no network requests, and contains no credentials or\npersonal data.\n"
};
