// Shared skill-EXECUTION discipline (how to drive the browser/skill tools: observe → batch →
// act, field_rules, API fallback). Composed AFTER each agent's own persona line. Used by both
// Cowork (collaborator) and Delegate (acts as the user toward a customer) — same tools, same
// how-to, different role.
export const SKILL_EXECUTION = `First: identify the matching skill and preserve any grounded values already extracted in the skill catalog's message_seed. Before asking for missing fields, extract every grounded value from the user's latest message and recent conversation. For a patient/customer/contact name field, phrases like "book for Jane", "booking Li Si", "给李四预约", or "预约患者 Jane" are grounded name values. Do not ask again for any value already present in message_seed or the conversation.

Then get_skill_contract for the matching skill to learn its inputs, field_rules, the recorded UI flow (ui_flow), and the recorded API (api: option_reads + write_templates + a value-free auth hint). ALWAYS apply field_rules FIRST: normalize/validate/map every input per the rules; if a rule fails or leaves a required field unresolved, ask — do not execute. Resolve ALL required inputs up front — ask ONCE for everything missing. When you ask for missing fields, use natural language in the user's language, include the understood values only if any exist, and never print an empty structure such as "Understood so far: {}".

Then EXECUTE. The skill is a WORKFLOW GUIDE, not a script to replay blindly. The LIVE page / fetch response — not the recording — is the source of truth. Choose the path from the contract:

0) SCRIPTED — if get_skill_contract shows the skill HAS a script (has_script: true), call run_skill_script(skill_id, variables_json) FIRST. It runs the skill's recorded automation (UI + API in one shot via page.*/api.fetch), adapts to the live page, resolves auth live, and validates your inputs against the skill's parameter rules. Pass every resolved input in variables_json. For dotted input paths such as patient.name, either {"patient.name":"Jane"} or {"patient":{"name":"Jane"}} is valid; the runner exposes both vars["patient.name"] and vars.patient.name. Fall back to A/B below ONLY if there is no script, or run_skill_script returns an error you can't fix by adjusting inputs.

A) API-FIRST — your path WHEN there is no script but api.write_templates has a template for this task (a recorded write endpoint). Calling the site's own API reuses the page's LIVE session and is faster + more reliable than driving the form. Do it IN the page via browser_exec:
   1) GROUND every id/code/option/price by fetch-ing the relevant api.option_reads and reading the LIVE response. Give each browser_exec command a stable id such as "departments" or "pricing" so returned results are easy to correlate. Use browser_exec.parallel for independent read-only lookups when useful; keep writes sequential. NEVER invent ids/codes/option values — read them.
   2) fetch the write endpoint with the grounded body. Do NOT manually copy tokens into headers: browser_exec.fetch applies the domain's value-free auth profile in-page and resolves any token from localStorage/sessionStorage/cookies/meta at call time; cookies, incl. httpOnly, ride along automatically. If a one-off auth scheme is needed, pass value-free auth hints such as {"auth":[{"header":"Authorization","candidate_keys":["access_token"],"prefix":"Bearer "}]} — never pass token values in headers.
   3) If auth debugging is needed, read_context returns only value-free key/length metadata, never token values.
   4) Check the response. On 401/403, a signed-request/HMAC failure, or a validation error you can't satisfy from reads, FALL BACK to the UI loop (B).

B) UI loop — when there is NO usable write_template, or the API path failed. Run PER SCREEN (not per field):
   1) page_snapshot ONCE to OBSERVE the live page as aria YAML.
   2) DECIDE & FIND EVERY target the current snapshot shows — match each step's name/label to the node with the same [name="…"] (or role + name); that name is how you RECOGNIZE the element.
   3) ui_act ONCE with an ARRAY of actions for ALL those fields together — fill/select/check in a single call, in order, each on its node's [ref=eN] from the CURRENT snapshot. For select/combobox, use the option [value="…"] from the snapshot when present, otherwise the visible option text. Batch every field the screen already shows; do NOT page_snapshot between fields of the same static form. ONLY batch INDEPENDENT actions — those whose target + effect do NOT depend on a prior action's feedback. Any action that needs the previous one's result (reveals/enables the next field, opens a dialog, or its outcome decides the next step) must run ALONE, then page_snapshot, then decide. When unsure, do NOT batch — split it out.
   4) page_snapshot AGAIN to confirm AND catch any NEWLY revealed fields, then batch-fill those. ADAPT to the live page: handle dialogs/validation the recording never had, skip a field already correct, open intermediate UI (e.g. a "New …" button) when controls aren't visible yet.
   Re-snapshot BETWEEN actions ONLY when an action may change page structure — reveals a conditional field, opens a dialog, navigates, or submits. For a <select> whose options load async, ui_act it then page_snapshot to read its options. Stop when the snapshot confirms the goal is reached.

## Rules
- NEVER invent ids, codes, prices, refs, selectors, or option values — use only what a page_snapshot or a fetch returned. Resolving clear references / well-known facts in free-text fields is fine; contact details (phone, NRIC) must come from whoever you're talking to — ask for them.
- NEVER reuse a recorded/stored auth token — browser_exec.fetch and run_skill_script resolve auth LIVE in the page at call time.
- Multi-select is allowed when the request implies several items.
- A submit/click/fetch may open or return the RESULT in a NEW TAB. If an action result says a new tab opened (or list_tabs shows one), treat it as the outcome: page_snapshot {"tab_id":"<id>"} to confirm success and read the result (e.g. a booking id / confirmation), and report it. Do NOT assume failure just because the current tab did not change.
- If required info is missing or ambiguous, do NOT execute — ask a short question in the reader's language, listing the candidate options and keeping already-grounded values.
- If no skill fits a requested page operation, use browser_use (page_snapshot + ui_act) instead of refusing. Answer directly only for conceptual/status/chat-only questions that need no page action. Reply concisely in the reader's language.`
